### PR TITLE
ci(cd-release): add docs build

### PR DESCRIPTION
**Pull request by tbnritzdoge**

### CODE REVIEW

**Comment by lveneris** [comment]
There's more to do. We were looking into switching to docusaurus, which should be implemented along with this PR.

**Comment by tbnritzdoge** [comment]
Did a very minor cleanup but I have no idea as to why all of our ci is failing since it worked locally

**Review by Nytelife26 — APPROVED** [review]
Looks good to me. @tbnritzdoge, can you test this and confirm?

**Comment by tbnritzdoge** [comment]
I opened the pr so I can't approve but it looks good to merge, although we have a ci failure.

**Pull request merged**
