### PR TITLE
docs: update usage

### PR DESCRIPTION
**Pull request by Vetlix**

### CODE REVIEW

**Review by tbnritzdoge — APPROVED** [review]

**Comment by lveneris** [comment]
This should likely be taken out of the repository root and shifted under our documentation site anyway.
Thoughts, @tbnritzdoge and @Vetlix?

**Comment by tbnritzdoge** [comment]
> This should likely be taken out of the repository root and shifted under our documentation site anyway.
> Thoughts, @tbnritzdoge and @Vetlix?

I personally like having everything in one repo but it's not a bad idea to separate the docs.

**Comment by Vetlix** [comment]
> 
> 
> This should likely be taken out of the repository root and shifted under our documentation site anyway.
> Thoughts, @tbnritzdoge and @Vetlix?

Seems like a decent idea to me

**Comment by lveneris** [comment]
> I personally like having everything in one repo but it's not a bad idea to separate the docs.

Our docs site is under the same repo. We would simply be taking USAGE.md out of the repository root and bundling it under our versioned documentation at `<root>/docs` instead.

**Comment by tbnritzdoge** [comment]
> > I personally like having everything in one repo but it's not a bad idea to separate the docs.
> 
> Our docs site is under the same repo. We would simply be taking USAGE.md out of the repository root and bundling it under our versioned documentation at `<root>/docs` instead.

Ah yes, that seems like a good idea. Sorry for misreading

**Comment by lveneris** [comment]
@Vetlix enable maintainer edits if it isn't already, it won't let me checkout your PR for some reason.

**Comment by Vetlix** [comment]
> @Vetlix enable maintainer edits if it isn't already, it won't let me checkout your PR for some reason.

It's already turned on, I don't usually turn it off
image

**Comment by lveneris** [comment]
Apologies for the delay, I'll give this a go after our test refactoring.

**Pull request merged**
