### PR TITLE
perf: remove spread operators and callback loops

### PR DESCRIPTION
**Pull request by tbnritzdoge**
benchmark - https://measurethat.net/Benchmarks/ShowResult/177377

### CODE REVIEW

**Review by Vetlix — DISMISSED** [review]
LGTM

**Comment by lveneris** [comment]
Unsure as to how this will play out with latest linting rules. Putting this on hold until docs gets merged.

**Comment by lveneris** [comment]
Designating as draft until the docs PR is merged and we can reach 100% coverage.

**Comment by tbnritzdoge** [comment]
changed to merge onto ci/docs rather than master

**Review by Nytelife26 — APPROVED** [review]
LGTM.

**Review by Vetlix — APPROVED** [review]

**Review by Vetlix — APPROVED** [review]
LGTM

**Pull request merged**
